### ISSUE TITLE
Copyright needs changed to Chesapeake Commons

### ISSUE THREAD

**Issue by rdawes1** [ChesapeakeCommons/FISH-static#1]
Copyright at the bottom says Penn State Cooperative Extension. That needs to be Chesapeake Commons

**Comment by brendandm** [comment]
![screenshot 2015-10-28 14 15 30](https://cloud.githubusercontent.com/assets/5325391/10798519/71cce3a0-7d7e-11e5-86ad-33f43353712d.png)
